spring.application.name=gisu-prototype
server.port=8080
spring.datasource.url=jdbc:mysql://localhost:3306/gisu
spring.datasource.username=root
spring.datasource.password=bankston123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.thymeleaf.cache=false
